ports:
  - port: 3000
  - port: 8000
image:
  file: .gitpod.dockerfile
tasks:
  - before: cd print-orders-app
    init: yarn install
    command: yarn start
  - before: >
      cd print-orders-api &&
      pip install mysql-connector &&
      pip install -U python-dotenv &&
      python init.py
    init: composer install
    command: >
      php artisan migrate:fresh --seed &&
      php -S localhost:8000 -t public
  - before: >
      cd print-orders-api &&
      export PATH=$PATH:$(pwd)/vendor/phpunit/phpunit
    command: >
      gp await-port 8000 &&
      phpunit
vscode:
  extensions:
    - jpoissonnier.vscode-styled-components@0.0.26:mtMkjJrLDD5C2eLocxpWzg==
    - CoenraadS.bracket-pair-colorizer@1.0.61:+jQByqALW0iXkhpd2yzYzQ==