ports:
  - port: 3000
image:
  file: .gitpod.dockerfile
tasks:
  - init: >
      cd print-orders-app &&
      yarn install
    command: >
      cd print-orders-app &&
      yarn start
vscode:
  extensions:
    - jpoissonnier.vscode-styled-components@0.0.26:mtMkjJrLDD5C2eLocxpWzg==